### PR TITLE
Added new config to set the path to save cassettes.

### PR DESCRIPTION
**Pull request by Bernardoow**
#160

### CODE REVIEW

**Comment by Bernardoow** [comment]
This modification works in this code:

`import betamax
from betamax.fixtures import unittest
import requests


def function():
    response = requests.get('https://httpbin.org/get')
    return response.json().get('url')


class IntegrationTestCase(unittest.BetamaxTestCase):
    CASSETTE_LIBRARY_DIR = "./bernardo"


class SpecificTestCase(IntegrationTestCase):
    def test_something(self):
        self.assertEqual(function(), 'https://httpbin.org/get')
`

**Comment by sigmavirus24** [comment]
Closing and then re-opening to trigger a new merged build

**Comment by sigmavirus24** [comment]
Thanks again @Bernardoow!

**Comment by Bernardoow** [comment]
@sigmavirus24 thanks for accepting !!!

**Comment by sigmavirus24** [comment]
@Bernardoow I'm wondering if you'd be interested in joining the team that maintains Betamax. You don't need to respond here, but I'll send you an invite to the organization right now. I'm happy to answer questions here or privately. 🎉

**Pull request merged**
